// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiSqlDbTest.Data;

#nullable disable

namespace WebApiSqlDbTest.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220607170835_UserAddedColumns2")]
    partial class UserAddedColumns2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("ClassLib.Target", b =>
                {
                    b.Property<int>("TargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AccessedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserAccessedId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserModifiedId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserOwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TargetId");

                    b.HasIndex("UserAccessedId");

                    b.HasIndex("UserModifiedId");

                    b.HasIndex("UserOwnerId");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("ClassLib.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClassLib.Target", b =>
                {
                    b.HasOne("ClassLib.User", "UserAccessed")
                        .WithMany("AccessedTargets")
                        .HasForeignKey("UserAccessedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassLib.User", "UserModified")
                        .WithMany("ModifiedTargets")
                        .HasForeignKey("UserModifiedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassLib.User", "UserOwner")
                        .WithMany("OwnedTargets")
                        .HasForeignKey("UserOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccessed");

                    b.Navigation("UserModified");

                    b.Navigation("UserOwner");
                });

            modelBuilder.Entity("ClassLib.User", b =>
                {
                    b.Navigation("AccessedTargets");

                    b.Navigation("ModifiedTargets");

                    b.Navigation("OwnedTargets");
                });
#pragma warning restore 612, 618
        }
    }
}
